### ISSUE TITLE
Parser: write test suite for expected behaviour gPermFieldsParser

### ISSUE THREAD

**Issue by JonathanLorimer** [JonathanLorimer/weft#10]
find relevant code [here](https://github.com/JonathanLorimer/weft/blob/master/src/Weft/Generics/QueryParser.hs#L44-L46)

**Comment by isovector** [comment]
is this still true? i wonder if the new permutations stuff obsoletes that comment. we should write a test suite :)

**Comment by JonathanLorimer** [comment]
Agreed, changing this issue to testing rather than a bug.
