### ISSUE TITLE
Parser: Handle spaces better in parseARawArg

### ISSUE THREAD

**Issue by JonathanLorimer** [JonathanLorimer/weft#11]
relevant code can be found [here](https://github.com/JonathanLorimer/weft/blob/master/src/Weft/Generics/QueryParser.hs#L148-L158)

**Comment by isovector** [comment]
What does better mean in this case?

**Comment by JonathanLorimer** [comment]
I may be mistaken, but I believe that arguments need to have spaces between parens to be parsed. The parser should be flexible enough to handle no-whitespace cases.

what is valid now:
```
query {
  userId( id: 1 )
  userName
}
```
what should also be valid
```
query {
  userId(id:1)
  userName
}
```
```
query {
  userId(id: 1)
  userName
}
```

If I am wrong, I am happy to close

**Comment by isovector** [comment]
This works today! Closing.
