### ISSUE TITLE
Parser should have support for query variables

### ISSUE THREAD

**Issue by isovector** [JonathanLorimer/weft#16]
If I write `foo (magic: $var)` in a query, then that `$var` should correspond to the variables passed in the original json request.

**Comment by JonathanLorimer** [comment]
@isovector I am going to pull the variables off, store them in a data structure, and provide them to the parser. I was thinking a simple key value map. Does that make sense?

**Comment by isovector** [comment]
Makes sense to me. Maybe we should make `queryParser` a `ReaderT TheVariables Parser (record 'Query)` in that case, rather than threading it throughout the generics.
