### ISSUE TITLE
Server: Parameterize Server Settings

### ISSUE THREAD

**Issue by JonathanLorimer** [JonathanLorimer/weft#7]
Allow the user to input their hostname and port for their server

**Comment by isovector** [comment]
Can we just do something like servant here, where our interface is `record 'Resovler -> Application`? Then the user can just run the resulting `Application` in everyday warp stuff.

**Comment by isovector** [comment]
eg `run 80 $ weft myResolver`

**Comment by JonathanLorimer** [comment]
is `myResolver` generic enough to handle any possible incoming query? If so that's a really elegant solution. Otherwise would could just have `myResolver` be a record of all resolvers. Regardless I think some form of this API makes sense.

**Comment by isovector** [comment]
`myResolver :: record 'Resolver` where that `record` is the top-level query type (or query/mutation/subscription set of types).

**Comment by JonathanLorimer** [comment]
do we have to manually apply the type or is it smart enough to figure that out?

**Comment by isovector** [comment]
It's smart enough!
