### ISSUE TITLE
Server: Turn a Request into a Response

### ISSUE THREAD

**Issue by JonathanLorimer** [JonathanLorimer/weft#8]
# Basically make the server work...

all this logic is handled in the [app function in Server.hs](https://github.com/JonathanLorimer/weft/blob/master/src/Server.hs#L37-L43)

Steps:
1. parse request into a Query of a particular type
2. pass the query to the resolver
3. take the Generically generated Response and turn it into JSON
4. Send it over the wire

**Comment by isovector** [comment]
Is it sufficient to just derive `ToJSON` for `record 'Response` for 3 here?

**Comment by JonathanLorimer** [comment]
Yeah, that should be enough, just wanted to record all the steps.
