### ISSUE TITLE
Parser:  Provide proper errors when parsing

### ISSUE THREAD

**Issue by JonathanLorimer** [JonathanLorimer/weft#9]
In response to TODO [here](https://github.com/JonathanLorimer/weft/blob/master/src/Weft/Generics/QueryParser.hs#L95)

**Comment by isovector** [comment]
This is probably easiest done by switching from attoparsec to something like megaparsec. It'll give us much better errors + line numbers. Although I'm not sure what we should do with that info --- do we return it to the client on a 4xx?

**Comment by JonathanLorimer** [comment]
Hmmm. I think we should delay this one. I thought that it might be valuable to return information about where the query in the request is malformed. But I think that the client might be able to get that information statically through introspection on the Schema.

**Comment by isovector** [comment]
i will accomplish this on my honor and with my bow and my sword
